version: '3'

networks:
  journly-network:
    external: true
services:
  db:
    container_name: journly_db
    image: postgres:15.3-alpine3.18
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_PORT}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - 'docker-journly-postgres:/var/lib/postgresql/data'
    networks:
      - journly-network
  redis:
    image: 'redislabs/rejson:2.0.0'
    ports:
      - '6379:6379'
    volumes:
      - 'docker-journly-redis:/data'
  journly:
    image: journly:latest
    container_name: journly
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SWAGGER_USERNAME: ${SWAGGER_USERNAME}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}
      PORT: 8000
    depends_on:
      - db
      - redis
  journly_1:
    image: journly:latest
    container_name: journly_1
    build: .
    ports:
      - "8001:8001"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SWAGGER_USERNAME: ${SWAGGER_USERNAME}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}
      PORT: 8001
    depends_on:
      - db
      - redis
    networks:
      - journly-network
  journly_2:
    image: journly:latest
    container_name: journly_2
    build: .
    ports:
      - "8002:8002"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SWAGGER_USERNAME: ${SWAGGER_USERNAME}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}
      PORT: 8002
    depends_on:
      - db
      - redis
    networks:
      - journly-network
volumes:
  docker-journly-redis:
  docker-journly-postgres:

