version: '3'

services:
  db:
    container_name: journly_db
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: journly_dev_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - 'docker-journly-postgres:/var/lib/postgresql/data'
  redis:
    image: 'redislabs/rejson:2.0.0'
    ports:
      - '6379:6379'
    volumes:
      - 'docker-journly-redis:/data'
  journly:
    image: journly:latest
    container_name: journly_dev_app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=journly_dev_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SWAGGER_USERNAME=Daniel_Brai
      - SWAGGER_PASSWORD=GenericPassword!123
      - PORT=8000
volumes:
  docker-journly-redis:
  docker-journly-postgres:

